# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11.2
      uses: actions/setup-python@v5
      with:
        python-version: "3.11.2"
        cache: "pip"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with ruff
      run: |
        python -m pip install ruff
        ruff --output-format=github .
      continue-on-error: true
    - uses: wntrblm/nox@2024.3.2
      with:
        python-versions: "3.11.2"
    - name: Test with nox
      run: |
        nox
