# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on: push

defaults:
  run:
    working-directory: "./software"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v4
      
    - uses: wntrblm/nox@main
      with:
        python-versions: "3.11.2"
    - name: Test with nox
      run: |
        nox
